services:
  postgres_daniel:
    image: postgres:16
    container_name: postgres-db-daniel
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
